= How to Run a Mock Mission

1. Start MavProxy at the location of the first sample waypoint.

    $ cd <path-to-ardupilot>/APMrover2
    $ sim_vehicle.py -l 37.659984,-121.8874624,0,45

2. Start the simulation. Zoom and center the waypoints, if you like.
Mouse wheel or 2-finger scroll zooms, control-shift-drag moves the
map around.

    $ roslaunch robo_magellan mock_mission.launch

3. In MavProxy, load the waypoint sample.

    rosrun mavros mavwp load data/sample.qgc-wpl.txt

4. Start the mission by arming the throttle and going into AUTO mode.

    $ rosservice call /mavros/cmd/arming "value: true"
    success: True
    result: 0
    $ rosservice call /mavros/set_mode "{custom_mode: 'AUTO'}"
    mode_sent: True

In rviz, you should see the rover follow the waypoints. When a cone is visible,
the heading to the cone is shown with a red arrow.

You can move the robot back to the starting point (approximately) using the command:

    $ rosservice call /mavros/set_mode "{custom_mode: 'RTL'}"
    
Then you can restart the mock mission by setting the mode to AUTO again, in step 4.
