:imagesdir: ./images
:toc: macro

= PRSG RoboMagellan ROS node

== What's in the repository?
The current use of this repository is to simulate a ROS node for the purposes of developing automated build.
link:http://programmingrobotsstudygroup.github.io/2017RoboMagellan.html[See PRSG's project website for project details]

== This Repository is integrated with Jenkins!
*Continuous Integration Etiquette:*

* mailto:ProgrammingRobotsStudyGroup@gmail.com?Subject=Request%20RoboMagellan%20Build%20Access"[Request access to to Jenkins notifications] if you commit code here.

* Check out the test suite. (still being developed).

* Build and run the tests locally before pushing to Github.

* If you build and run the tests successfully locally, go ahead and push to Github.

* If you push to Jenkins and get an email failure, please fix it immediately!

== Prepare your System

=== 1. Install Ubuntu and ROS to UP and Test

* link:https://01.org/developerjourney/recipe/intel-realsense-robotic-development-kit[Follow Intel's steps].
* You should be able to run RViz.

=== 2. Install Chrony
Chrony implements Network Time Protocol, (NTP), in order to keep your system clock accurate. It is designed to work with intermittent network connections. 
----
sudo apt-get install chrony
----

=== 3. Configure Zeroconf
Add this line to your .bashrc file on the UP and your development machine. Reboot.
----
export ROS_HOSTNAME=`echo $HOSTNAME`.local
----

Reboot the machine and test configuration from both ends. 
If you named your machine 'robot' as advised in Intel documents, you should be able to ping the robot's processor from your machine. Substitue robot for your machine name if ou elected to use a different name.
----
$ ping robot.local
----

To test your laptop/development machine, 
----
$ ssh robot@robot.local
$ robot@robot.local's password: 
robot@robot:~$ ping my_machine.local
----

=== 4. Get the Code
You will need ROS Kinetic installed on your machine. Start by fetching the repository.

----
cd catkin_ws/src
git clone https://github.com/ProgrammingRobotsStudyGroup/robo_magellan.git
----

Then run the installation script:
----
./install_Victoria.sh
----
