= To-Do List

Below, *ISSUE* means a GitHub issue has been created instead.

- (*DONE*) shouldn't need intermediate waypoint to trigger EXPECTING_CONE
- (*ISSUE*) have to handle case where cone waypoint is achieved before seeing cone
- need to limit time of reverse
- (*ISSUE*) have to handle case where in MANUAL mode and don't see cone
- (*ISSUE*) mock_cone_detector creates infinite area and overflows h
- (*DONE*) new waypoints shorter than old don't delete existing waypoints
- (*ISSUE*) adjust waypoints for start position and cone position
- (*ISSUE*) cone area goes down when very close to cone
- (*DONE*) parameterize throttle and steering PWM values
- (*DONE*) touch sensor does not work
- (*DONE*) cone detection in bright light does not work
- (*ISSUE*) GUIDED mode does not work
- (*DONE*) Encode PWM values or range set to use in the waypoints file
- (*ISSUE*) If waypoint encountered before cone is seen, rover goes into HOLD mode
with no recovery. Needs to be fixed.

== Possible To-Do

- (*DONE*) Change from using WP_SPEED to CRUISE_SPEED. (Seems to be used by Vicky,
while WP_SPEED is not.)
- Have a way of manually triggering parameter reload

== Notes

MAV_CMD_DO_SET_HOME appears to reset the map origin, as well as zero the
offset between the map origin and base_link (for /mavros/local_position/pose
and /mavros/local_position/odom).
