#! /bin/bash

function usage() {
    echo "usage: rosrun robo_magellan exec (start|reset|load|pull|adjust)"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

case $1 in
    start)
        rostopic pub -1 /exec_cmd_simple std_msgs/String "data: 'START_EXEC'"
        ;;
    reset)
        rostopic pub -1 /exec_cmd_simple std_msgs/String "data: 'RESET'"
        ;;
    load)
        rosrun mavros mavwp load $2
        ;;
    adjust)
        rostopic pub -1 /exec_cmd_simple std_msgs/String "data: 'ADJUST_WAYPOINTS'"
        ;;
    pull)
        rosservice call /mavros/mission/pull "{}"
        ;;
    *)
        usage
        ;;
esac
